services:
  app:
    ports:
      - "8081:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: make dev
    depends_on:
      db:
        condition: service_healthy
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

volumes:
  app_node_modules: