name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file from .env.example
        run: cp .env.example .env

      - name: Run tests using Docker Compose
        run: docker compose --env-file .env -f docker-compose.yml up --abort-on-container-exit

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build production docker image
        run: docker build -f Dockerfile.production -t dcdim/devops-for-programmers-project-74:latest .

      - name: Push production docker image
        run: docker push dcdim/devops-for-programmers-project-74:latest